#!/bin/sh

PACKAGE_VERSION=1.8.5
PACKAGE_FILE_NAME=vagrant_1.8.5_x86_64.deb
PACKAGE_DOWNLOAD_LINK=https://releases.hashicorp.com/vagrant/$PACKAGE_VERSION/$PACKAGE_FILE_NAME

wget $PACKAGE_DOWNLOAD_LINK
sudo dpkg -i $PACKAGE_FILE_NAME
rm $PACKAGE_FILE_NAME
